export const CountryCodes = {
    "4": "afg",
    "8": "alb",
    "10": "ata",
    "12": "dza",
    "16": "asm",
    "20": "and",
    "24": "ago",
    "28": "atg",
    "31": "aze",
    "32": "arg",
    "36": "aus",
    "40": "aut",
    "44": "bhs",
    "48": "bhr",
    "50": "bgd",
    "51": "arm",
    "52": "brb",
    "56": "bel",
    "60": "bmu",
    "64": "btn",
    "68": "bol",
    "70": "bih",
    "72": "bwa",
    "74": "bouisl",
    "76": "bra",
    "84": "blz",
    "86": "iot",
    "90": "slb",
    "92": "vgb",
    "96": "brn",
    "100": "bgr",
    "104": "mmr",
    "108": "bdi",
    "112": "blr",
    "116": "khm",
    "120": "cmr",
    "124": "can",
    "132": "cpv",
    "136": "cym",
    "140": "caf",
    "144": "lka",
    "148": "tcd",
    "152": "chl",
    "156": "chn",
    "158": "twn",
    "162": "cxr",
    "166": "cck",
    "170": "col",
    "174": "com",
    "175": "myt",
    "178": "cog",
    "180": "cod",
    "184": "cok",
    "188": "cri",
    "191": "hrv",
    "192": "cub",
    "196": "cyp",
    "203": "cze",
    "204": "ben",
    "208": "dnk",
    "212": "dma",
    "214": "dom",
    "218": "ecu",
    "222": "slv",
    "226": "gnq",
    "231": "eth",
    "232": "eri",
    "233": "est",
    "234": "fro",
    "238": "flk",
    "239": "sgero_a_ssandw",
    "242": "fji",
    "246": "fin",
    "248": "ala",
    "250": "fra",
    "254": "guf",
    "258": "pyf",
    "262": "dji",
    "266": "gab",
    "268": "geo",
    "270": "gmb",
    "275": "pse",
    "276": "deu",
    "288": "gha",
    "292": "gib",
    "296": "kir",
    "300": "grc",
    "304": "grl",
    "308": "grd",
    "312": "glp",
    "316": "gum",
    "320": "gtm",
    "324": "gin",
    "328": "guy",
    "332": "hti",
    "334": "heard_a_mcd",
    "336": "hos",
    "340": "hnd",
    "344": "hkg",
    "348": "hun",
    "352": "isl",
    "356": "ind",
    "360": "idn",
    "364": "irn",
    "368": "irq",
    "372": "irl",
    "376": "isr",
    "380": "ita",
    "384": "civ",
    "388": "jam",
    "392": "jpn",
    "398": "kaz",
    "400": "jor",
    "404": "ken",
    "408": "prk",
    "410": "kor",
    "414": "kwt",
    "417": "kgz",
    "418": "lao",
    "422": "lbn",
    "426": "lso",
    "428": "lva",
    "430": "lbr",
    "434": "lby",
    "438": "lie",
    "440": "ltu",
    "442": "lux",
    "446": "mac",
    "450": "mdg",
    "454": "mwi",
    "458": "mys",
    "462": "mdv",
    "466": "mli",
    "470": "mlt",
    "474": "mtq",
    "478": "mrt",
    "480": "mus",
    "484": "mex",
    "492": "mco",
    "496": "mng",
    "498": "mda",
    "499": "mne",
    "500": "msr",
    "504": "mar",
    "508": "moz",
    "512": "omn",
    "516": "nam",
    "520": "nru",
    "524": "npl",
    "528": "nld",
    "531": "nld_curacao",
    "533": "abw",
    "534": "sxm",
    "540": "ncl",
    "548": "vut",
    "554": "nzl",
    "558": "nic",
    "562": "ner",
    "566": "nga",
    "570": "niu",
    "574": "nfk",
    "578": "nor",
    "580": "mnp",
    "581": "usa_minor_out_isl",
    "583": "fsm",
    "584": "mhl",
    "585": "plw",
    "586": "pak",
    "591": "pan",
    "598": "png",
    "600": "pry",
    "604": "per",
    "608": "phl",
    "612": "pcn",
    "616": "pol",
    "620": "prt",
    "624": "gnb",
    "626": "tls",
    "630": "pri",
    "634": "qat",
    "638": "reu",
    "642": "rou",
    "643": "rus",
    "646": "rwa",
    "652": "stbar",
    "654": "shn",
    "659": "kna",
    "660": "aia",
    "662": "lca",
    "663": "maf",
    "666": "spm",
    "670": "vct",
    "674": "smr",
    "678": "stp",
    "682": "sau",
    "686": "sen",
    "688": "srb",
    "690": "syc",
    "694": "sle",
    "702": "sgp",
    "703": "svk",
    "704": "vnm",
    "705": "svn",
    "706": "som",
    "710": "zaf",
    "716": "zwe",
    "724": "esp",
    "728": "ssd",
    "729": "sdn",
    "732": "esh",
    "740": "sur",
    "744": "sjm",
    "748": "swz",
    "752": "swe",
    "756": "che",
    "760": "syr",
    "762": "tjk",
    "764": "tha",
    "768": "tgo",
    "772": "tkl",
    "776": "ton",
    "780": "tto",
    "784": "are",
    "788": "tun",
    "792": "tur",
    "795": "tkm",
    "796": "tca",
    "798": "tuv",
    "800": "uga",
    "804": "ukr",
    "807": "mkd",
    "818": "egy",
    "826": "gbr",
    "831": "gbg",
    "832": "jey",
    "833": "gbm",
    "834": "tza",
    "840": "usa",
    "850": "vir",
    "854": "bfa",
    "858": "ury",
    "860": "uzb",
    "862": "ven",
    "876": "wlf",
    "882": "wsm",
    "887": "yem",
    "894": "zmb",
    "Abkhazia": "abkh",
    "GE-AB": "abkh",
    "ABW": "abw",
    "Aruba": "abw",
    "AW": "abw",
    "AF": "afg",
    "AFG": "afg",
    "Afghanistan": "afg",
    "Islamic Republic of Afghanistan": "afg",
    "AGO": "ago",
    "Angola": "ago",
    "AO": "ago",
    "AI": "aia",
    "AIA": "aia",
    "Anguilla": "aia",
    "Akrotiri and Dhekelia": "akr_a_dhe",
    "Akrotiri_Dhekelia": "akr_a_dhe",
    "Åland": "ala",
    "AALAND ISLANDS": "ala",
    "ALA": "ala",
    "AX": "ala",
    "AL": "alb",
    "ALB": "alb",
    "Albania": "alb",
    "AD": "and",
    "AND": "and",
    "Andorra": "and",
    "AN": "ant",
    "Neth. Antilles": "ant",
    "Netherland Antilles": "ant",
    "Netherlands Antilles": "ant",
    "AE": "are",
    "ARE": "are",
    "UAE": "are",
    "United Arab Emirates": "are",
    "AR": "arg",
    "ARG": "arg",
    "Argentina": "arg",
    "AM": "arm",
    "ARM": "arm",
    "Armenia": "arm",
    "American Samoa": "asm",
    "AS": "asm",
    "ASM": "asm",
    "Antarctica": "ata",
    "AQ": "ata",
    "ATA": "ata",
    "AG": "atg",
    "Antigua & Barbuda": "atg",
    "Antigua and Barbuda": "atg",
    "ATG": "atg",
    "AU": "aus",
    "AUS": "aus",
    "Australia": "aus",
    "AT": "aut",
    "Austria": "aut",
    "AUT": "aut",
    "AZ": "aze",
    "AZE": "aze",
    "Azerbaijan": "aze",
    "BDI": "bdi",
    "BI": "bdi",
    "Burundi": "bdi",
    "BE": "bel",
    "BEL": "bel",
    "Belgium": "bel",
    "BEN": "ben",
    "Benin": "ben",
    "BJ": "ben",
    "BF": "bfa",
    "BFA": "bfa",
    "Burkina Faso": "bfa",
    "Burkina_Faso": "bfa",
    "Bangladesh": "bgd",
    "BD": "bgd",
    "BGD": "bgd",
    "BG": "bgr",
    "BGR": "bgr",
    "Bulgaria": "bgr",
    "Bahrain": "bhr",
    "Bahrein": "bhr",
    "BH": "bhr",
    "BHR": "bhr",
    "Bahamas": "bhs",
    "B'ahamas', The": "bhs",
    "BHS": "bhs",
    "BS": "bhs",
    "The Bahamas": "bhs",
    "BA": "bih",
    "BIH": "bih",
    "Bosnia": "bih",
    "Bosnia & Herzegovina": "bih",
    "Bosnia & Herzegovinia": "bih",
    "Bosnia and H.": "bih",
    "Bosnia and Herzegovina": "bih",
    "BOSNIA AND HERZEGOWINA": "bih",
    "Bosnia Herzegovena": "bih",
    "Bosnia-Herzegovina": "bih",
    "Belarus": "blr",
    "BLR": "blr",
    "BY": "blr",
    "Belize": "blz",
    "BLZ": "blz",
    "BZ": "blz",
    "Bermuda": "bmu",
    "BM": "bmu",
    "BMU": "bmu",
    "BO": "bol",
    "BOL": "bol",
    "Bolivia": "bol",
    "Bolivia (Plurinational State of)": "bol",
    "Bolivia Plurinational States of": "bol",
    "PLURINATIONAL STATE OF BOLIVIA": "bol",
    "Bouvet Island": "bouisl",
    "BV": "bouisl",
    "BVT": "bouisl",
    "BR": "bra",
    "BRA": "bra",
    "Brazil": "bra",
    "Barbados": "brb",
    "BB": "brb",
    "BRB": "brb",
    "BN": "brn",
    "BRN": "brn",
    "Brunei": "brn",
    "Brunei (Darussalam)": "brn",
    "Brunei Darussalam": "brn",
    "Bhutan": "btn",
    "BT": "btn",
    "BTN": "btn",
    "Botswana": "bwa",
    "BW": "bwa",
    "BWA": "bwa",
    "CAF": "caf",
    "CAR": "caf",
    "Central AfR": "caf",
    "Central African Rep.": "caf",
    "Central African Republic": "caf",
    "CF": "caf",
    "CA": "can",
    "CAN": "can",
    "Canada": "can",
    "CC": "cck",
    "CCK": "cck",
    "COCOS (KEELING) ISLANDS": "cck",
    "Cocos Island": "cck",
    "Channel Islands": "chanisl",
    "Channel_Islands": "chanisl",
    "CH": "che",
    "CHE": "che",
    "Switzerland": "che",
    "Czechoslovakia": "cheslo",
    "Chile": "chl",
    "CHL": "chl",
    "CL": "chl",
    "China": "chn",
    "China (Mainland)": "chn",
    "CHN": "chn",
    "CN": "chn",
    "CI": "civ",
    "CIV": "civ",
    "Cote D Ivoire": "civ",
    "Cote Divoire": "civ",
    "Cote d'Ivoire": "civ",
    "Côte d'Ivoire": "civ",
    "Cote_dIvoire": "civ",
    "Ivory Coast": "civ",
    "Cameroon": "cmr",
    "CM": "cmr",
    "CMR": "cmr",
    "Republic Of Cameroon": "cmr",
    "CD": "cod",
    "COD": "cod",
    "Congo - Kinshasa": "cod",
    "Congo (Democratic Republic of the)": "cod",
    "Congo [DRC]": "cod",
    "Congo Dem Rep": "cod",
    "Congo DR": "cod",
    "CONGO, DEM REP": "cod",
    "C'ongo', Dem. Rep.": "cod",
    "CONGO, Democratic Republic of (was Zaire)": "cod",
    "Congo_Democratic_Republic": "cod",
    "Dem. Rep. Congo": "cod",
    "Democratic Republic of Congo": "cod",
    "Democratic Republic Of The Congo": "cod",
    "Democratic Republic Of The Congo (Formerly Zaire)": "cod",
    "CG": "cog",
    "COG": "cog",
    "Cong": "cog",
    "Congo": "cog",
    "Congo - Brazzaville": "cog",
    "Congo (Republic of)": "cog",
    "Congo Brazzaville": "cog",
    "C'ongo', Rep.": "cog",
    "CONGO, Republic of": "cog",
    "CONGO, REPUBLIC OF THE": "cog",
    "Republic of Congo": "cog",
    "CK": "cok",
    "COK": "cok",
    "Cook Is": "cok",
    "Cook Islands": "cok",
    "CO": "col",
    "COL": "col",
    "Colombia": "col",
    "COM": "com",
    "Comores": "com",
    "Comoros": "com",
    "KM": "com",
    "Cabo Verde": "cpv",
    "Cape Verde": "cpv",
    "CPV": "cpv",
    "CV": "cpv",
    "Costa Rica": "cri",
    "CR": "cri",
    "CRI": "cri",
    "CU": "cub",
    "CUB": "cub",
    "Cuba": "cub",
    "Christmas Island": "cxr",
    "CX": "cxr",
    "CXR": "cxr",
    "Cayman Islands": "cym",
    "CYM": "cym",
    "KY": "cym",
    "CY": "cyp",
    "CYP": "cyp",
    "Cyprus": "cyp",
    "Northern Cyprus": "cyp_nor",
    "Northern_Cyprus": "cyp_nor",
    "CZ": "cze",
    "CZE": "cze",
    "Czech Rep": "cze",
    "Czech Rep.": "cze",
    "Czech Republic": "cze",
    "DE": "deu",
    "DEU": "deu",
    "Germany": "deu",
    "East Germany": "deu_east",
    "East_Germany": "deu_east",
    "FORMER GERMAN DEMOCRATIC REPUBLIC": "deu_east",
    "FEDERAL REPUBLIC OF GERMANY": "deu_west",
    "West Germany": "deu_west",
    "West_Germany": "deu_west",
    "DJ": "dji",
    "DJI": "dji",
    "Djibouti": "dji",
    "DM": "dma",
    "DMA": "dma",
    "Dominica": "dma",
    "Denmark": "dnk",
    "DK": "dnk",
    "DNK": "dnk",
    "DO": "dom",
    "DOM": "dom",
    "Dom.R.": "dom",
    "Dominican Rep.": "dom",
    "Dominican Republic": "dom",
    "Dominican_Republic": "dom",
    "DominicanRep": "dom",
    "Algeria": "dza",
    "DZ": "dza",
    "DZA": "dza",
    "EC": "ecu",
    "ECU": "ecu",
    "Ecuador": "ecu",
    "EG": "egy",
    "EGY": "egy",
    "Egypt": "egy",
    "EgyptArab Rep.": "egy",
    "ER": "eri",
    "ERI": "eri",
    "Eritrea": "eri",
    "Eritrea and Ethiopia": "eri_a_eth",
    "Eritrea_Ethiopia": "eri_a_eth",
    "EH": "esh",
    "ESH": "esh",
    "Western Sahara": "esh",
    "ES": "esp",
    "ESP": "esp",
    "Spain": "esp",
    "EE": "est",
    "EST": "est",
    "Estonia": "est",
    "ET": "eth",
    "ETH": "eth",
    "Ethiopia": "eth",
    "FI": "fin",
    "FIN": "fin",
    "Finland": "fin",
    "Fiji": "fji",
    "FJ": "fji",
    "FJI": "fji",
    "Falkland Is (Malvinas)": "flk",
    "Falkland Islands": "flk",
    "Falkland Islands (Malvinas)": "flk",
    "FK": "flk",
    "FLK": "flk",
    "FR": "fra",
    "FRA": "fra",
    "France": "fra",
    "France (Including Monaco)": "fra",
    "French Southern and Antarctic Lands": "fra_antarc",
    "TF": "fra_antarc",
    "Clipperton": "fra_clipperton",
    "CP": "fra_clipperton",
    "Faeroe Islands": "fro",
    "Faroe Islands": "fro",
    "FO": "fro",
    "FRO": "fro",
    "Federated States of Micronesia": "fsm",
    "FM": "fsm",
    "FSM": "fsm",
    "Micronesia": "fsm",
    "Micronesia (Fed. States of)": "fsm",
    "Micronesia (Federated States of": "fsm",
    "Micronesia (Federated States of)": "fsm",
    "MicronesiaFed. Sts.": "fsm",
    "MICRONESIAFEDERATED STATES OF": "fsm",
    "GA": "gab",
    "GAB": "gab",
    "Gabon": "gab",
    "GG": "gbg",
    "GGY": "gbg",
    "Guernsey": "gbg",
    "IM": "gbm",
    "IMN": "gbm",
    "Isle of Man": "gbm",
    "GB": "gbr",
    "GBR": "gbr",
    "UK": "gbr",
    "Unitd Kingdm": "gbr",
    "United Kingdom": "gbr",
    "United Kingdom of Great Britain and Northern Ireland": "gbr",
    "GE": "geo",
    "GEO": "geo",
    "Georgia": "geo",
    "http://en.wikipedia.org/wiki/ISO_3166-2:GE": "geo",
    "GH": "gha",
    "GHA": "gha",
    "Ghana": "gha",
    "GI": "gib",
    "GIB": "gib",
    "Gibraltar": "gib",
    "GIN": "gin",
    "GN": "gin",
    "Guinea": "gin",
    "GLP": "glp",
    "GP": "glp",
    "Guadeloupe": "glp",
    "Gambia": "gmb",
    "Gambia The": "gmb",
    "GambiaThe": "gmb",
    "GM": "gmb",
    "GMB": "gmb",
    "The Gambia": "gmb",
    "GNB": "gnb",
    "Guinea Bissau": "gnb",
    "GuineaBiss": "gnb",
    "Guinea-Bissau": "gnb",
    "GW": "gnb",
    "Equa Guinea": "gnq",
    "Equatorial Guinea": "gnq",
    "GNQ": "gnq",
    "GQ": "gnq",
    "GR": "grc",
    "GRC": "grc",
    "Greece": "grc",
    "GD": "grd",
    "GRD": "grd",
    "Grenada": "grd",
    "GL": "grl",
    "Greenland": "grl",
    "GRL": "grl",
    "GT": "gtm",
    "GTM": "gtm",
    "Guatemala": "gtm",
    "French Guiana": "guf",
    "GF": "guf",
    "GUF": "guf",
    "Guyana (Fr.)": "guf",
    "GU": "gum",
    "Guam": "gum",
    "GUM": "gum",
    "GUY": "guy",
    "Guyana": "guy",
    "GY": "guy",
    "Heard and McDonald Islands": "heard_a_mcd",
    "HM": "heard_a_mcd",
    "HMD": "heard_a_mcd",
    "ChinaHong Kong SAR": "hkg",
    "HK": "hkg",
    "HKG": "hkg",
    "Hong Kong": "hkg",
    "Hong Kong SAR": "hkg",
    "Hong Kong SARChina": "hkg",
    "Hong KongChina": "hkg",
    "Hong KongChina (SAR)": "hkg",
    "Hongkong": "hkg",
    "HN": "hnd",
    "HND": "hnd",
    "Honduras": "hnd",
    "Holy See": "hos",
    "Holy_See": "hos",
    "VA": "hos",
    "VAT": "hos",
    "Vatican City": "hos",
    "Croatia": "hrv",
    "CROATIA (local name: Hrvatska)": "hrv",
    "HR": "hrv",
    "HRV": "hrv",
    "Haiti": "hti",
    "HT": "hti",
    "HTI": "hti",
    "HU": "hun",
    "HUN": "hun",
    "Hungary": "hun",
    "ID": "idn",
    "IDN": "idn",
    "Indonesia": "idn",
    "IN": "ind",
    "IND": "ind",
    "India": "ind",
    "British Indian Ocean Territory": "iot",
    "IO": "iot",
    "IOT": "iot",
    "IE": "irl",
    "Ireland": "irl",
    "IRL": "irl",
    "IR": "irn",
    "Iran": "irn",
    "Iran (Islamic Rep. of)": "irn",
    "IRAN (ISLAMIC REPUBLIC OF)": "irn",
    "IranIslamic Rep.": "irn",
    "IranIslamic Rep. of": "irn",
    "IRN": "irn",
    "Islamic Republic Of Iran": "irn",
    "IQ": "irq",
    "Iraq": "irq",
    "IRQ": "irq",
    "Iceland": "isl",
    "IS": "isl",
    "ISL": "isl",
    "IL": "isr",
    "ISR": "isr",
    "Israel": "isr",
    "IT": "ita",
    "ITA": "ita",
    "Italy": "ita",
    "Italy (Including San Marino)": "ita",
    "JAM": "jam",
    "Jamaica": "jam",
    "JM": "jam",
    "JE": "jey",
    "Jersey": "jey",
    "JEY": "jey",
    "JO": "jor",
    "JOR": "jor",
    "Jordan": "jor",
    "Japan": "jpn",
    "JAPAN (EXCLUDING THE RUYUKU ISLANDS)": "jpn",
    "JP": "jpn",
    "JPN": "jpn",
    "KAZ": "kaz",
    "Kazakhstan": "kaz",
    "KZ": "kaz",
    "KE": "ken",
    "KEN": "ken",
    "Kenya": "ken",
    "KG": "kgz",
    "KGZ": "kgz",
    "Kyrgyz": "kgz",
    "Kyrgyz Republic": "kgz",
    "Kyrgyz_Republic": "kgz",
    "Kyrgyzstan": "kgz",
    "Cambodia": "khm",
    "KH": "khm",
    "KHM": "khm",
    "KI": "kir",
    "KIR": "kir",
    "Kiribati": "kir",
    "KN": "kna",
    "KNA": "kna",
    "Saint Kitts & Nevis": "kna",
    "Saint Kitts and Nevis": "kna",
    "St. Kitts and Nevis": "kna",
    "St. Kitts-Nevis": "kna",
    "KOR": "kor",
    "Korea (Rep. of)": "kor",
    "Korea (Republic of)": "kor",
    "Korea Rep": "kor",
    "Korea South": "kor",
    "KoreaRep.": "kor",
    "KoreaRep. of": "kor",
    "KOREAREPUBLIC OF": "kor",
    "KoreaSouth": "kor",
    "KR": "kor",
    "Republic Of Korea": "kor",
    "South Korea": "kor",
    "KoreaUnited": "korea_union",
    "United Korea": "korea_union",
    "United Korea (former)": "korea_union",
    "United_Korea": "korea_union",
    "Kosovo": "kos",
    "XK": "kos",
    "Kuwait": "kwt",
    "KW": "kwt",
    "KWT": "kwt",
    "LA": "lao",
    "Lao": "lao",
    "Lao P.D.R.": "lao",
    "Lao PDR": "lao",
    "Lao People S Democratic Republic": "lao",
    "Lao People's Democratic Republic": "lao",
    "Lao People's Dem. Rep.": "lao",
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC": "lao",
    "Laos": "lao",
    "LB": "lbn",
    "LBN": "lbn",
    "Lebanon": "lbn",
    "LBR": "lbr",
    "Liberia": "lbr",
    "LR": "lbr",
    "LBY": "lby",
    "Libya": "lby",
    "Libyan Arab Jamahiriya": "lby",
    "Libyan Arab Jamahiriyah": "lby",
    "LY": "lby",
    "LC": "lca",
    "LCA": "lca",
    "Saint Lucia": "lca",
    "St. Lucia": "lca",
    "St.Lucia": "lca",
    "LI": "lie",
    "LIE": "lie",
    "Liechtenstein": "lie",
    "LK": "lka",
    "LKA": "lka",
    "Sri Lanka": "lka",
    "Lesotho": "lso",
    "LS": "lso",
    "LSO": "lso",
    "Lithuania": "ltu",
    "LT": "ltu",
    "LTU": "ltu",
    "LU": "lux",
    "LUX": "lux",
    "Luxembourg": "lux",
    "Latvia": "lva",
    "LV": "lva",
    "LVA": "lva",
    "ChinaMacao SAR": "mac",
    "MAC": "mac",
    "Macao": "mac",
    "Macao SARChina": "mac",
    "MacaoChina": "mac",
    "Macau": "mac",
    "MACAU SPECIAL ADMINISTRATIVE REGION OF CHINA": "mac",
    "MO": "mac",
    "MAF": "maf",
    "MF": "stmar",
    "St. Martin (French part)": "maf",
    "MA": "mar",
    "MAR": "mar",
    "Morocc": "mar",
    "Morocco": "mar",
    "MC": "mco",
    "MCO": "mco",
    "Monaco": "mco",
    "MD": "mda",
    "MDA": "mda",
    "Moldova": "mda",
    "Moldova (Republic of)": "mda",
    "MoldovaRep. of": "mda",
    "MOLDOVAREPUBLIC OF": "mda",
    "Republic Of Moldov": "mda",
    "Republic of Moldova": "mda",
    "Madagascar": "mdg",
    "MDG": "mdg",
    "MG": "mdg",
    "Maldives": "mdv",
    "MDV": "mdv",
    "MV": "mdv",
    "MEX": "mex",
    "Mexico": "mex",
    "MX": "mex",
    "Marshall Islands": "mhl",
    "MH": "mhl",
    "MHL": "mhl",
    "Macedonia": "mkd",
    "Macedonia [FYROM]": "mkd",
    "MacedoniaFYR": "mkd",
    "MACEDONIATHE FORMER YUGOSLAV REPUBLIC OF": "mkd",
    "MK": "mkd",
    "MKD": "mkd",
    "T.F.Y.R. Macedonia": "mkd",
    "TFYR Macedonia": "mkd",
    "The former Yugoslav Republic of Macedonia": "mkd",
    "Mali": "mli",
    "ML": "mli",
    "MLI": "mli",
    "Malta": "mlt",
    "MLT": "mlt",
    "MT": "mlt",
    "Burma": "mmr",
    "MM": "mmr",
    "MMR": "mmr",
    "Myanmar": "mmr",
    "MYANMAR (FORMERLY BURMA)": "mmr",
    "Myanmar [Burma]": "mmr",
    "Myanmar/Burma": "mmr",
    "ME": "mne",
    "MNE": "mne",
    "Montenegro": "mne",
    "MN": "mng",
    "MNG": "mng",
    "Mongoli": "mng",
    "Mongolia": "mng",
    "MNP": "mnp",
    "MP": "mnp",
    "Northern Mariana Islands": "mnp",
    "MOZ": "moz",
    "Mozambique": "moz",
    "MZ": "moz",
    "Mauritania": "mrt",
    "MR": "mrt",
    "MRT": "mrt",
    "Montserra": "msr",
    "Montserrat": "msr",
    "MS": "msr",
    "MSR": "msr",
    "Martinique": "mtq",
    "MQ": "mtq",
    "MTQ": "mtq",
    "Mauritius": "mus",
    "MU": "mus",
    "MUS": "mus",
    "Malawi": "mwi",
    "MW": "mwi",
    "MWI": "mwi",
    "Malaysia": "mys",
    "MY": "mys",
    "MYS": "mys",
    "Mayotte": "myt",
    "MYT": "myt",
    "YT": "myt",
    "NAM": "nam",
    "Namibia": "nam",
    "NC": "ncl",
    "NCL": "ncl",
    "New Caledonia": "ncl",
    "NE": "ner",
    "NER": "ner",
    "Niger": "ner",
    "NF": "nfk",
    "NFK": "nfk",
    "Norfolk Island": "nfk",
    "NG": "nga",
    "NGA": "nga",
    "Nigeria": "nga",
    "Ngorno_Karabakh": "ngokar",
    "Ngorno-Karabakh": "ngokar",
    "NI": "nic",
    "NIC": "nic",
    "Nicaragua": "nic",
    "NIU": "niu",
    "Niue": "niu",
    "NU": "niu",
    "Netherlands": "nld",
    "NL": "nld",
    "NLD": "nld",
    "The Netherlands": "nld",
    "CURACAO": "nld_curacao",
    "Curaçao": "nld_curacao",
    "CUW": "nld_curacao",
    "CW": "nld_curacao",
    "NO": "nor",
    "NOR": "nor",
    "Norway": "nor",
    "Nepal": "npl",
    "NP": "npl",
    "NPL": "npl",
    "Nauru": "nru",
    "NR": "nru",
    "NRU": "nru",
    "New Zealand": "nzl",
    "NZ": "nzl",
    "NZL": "nzl",
    "OM": "omn",
    "Oman": "omn",
    "OMN": "omn",
    "PAK": "pak",
    "Pakistan": "pak",
    "PK": "pak",
    "PA": "pan",
    "PAN": "pan",
    "Panama": "pan",
    "PCN": "pcn",
    "Pitcairn": "pcn",
    "Pitcairn Islands": "pcn",
    "PN": "pcn",
    "PE": "per",
    "PER": "per",
    "Peru": "per",
    "PH": "phl",
    "Philippines": "phl",
    "PHL": "phl",
    "Palau": "plw",
    "PLW": "plw",
    "PW": "plw",
    "Papua New Guinea": "png",
    "Papua NG": "png",
    "PG": "png",
    "PNG": "png",
    "PL": "pol",
    "POL": "pol",
    "Poland": "pol",
    "PR": "pri",
    "PRI": "pri",
    "Puerto Rico": "pri",
    "Dem. People's Rep. Korea": "prk",
    "Dem. People's Rep. of Korea": "prk",
    "Democratic People S Republic Of Korea": "prk",
    "Democratic People's Republic of Korea": "prk",
    "Korea (Democratic People's Rep. of)": "prk",
    "Korea DPR": "prk",
    "Korea North": "prk",
    "K'orea', Dem. Rep.": "prk",
    "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": "prk",
    "K'orea', Democratic Republic of": "prk",
    "K'orea', North": "prk",
    "KP": "prk",
    "North Korea": "prk",
    "PRK": "prk",
    "Portugal": "prt",
    "PRT": "prt",
    "PT": "prt",
    "Paraguay": "pry",
    "PRY": "pry",
    "PY": "pry",
    "Occupied Palestinian Territory": "pse",
    "OPT": "pse",
    "Palestine": "pse",
    "PalestineState of": "pse",
    "Palestinian territories": "pse",
    "PALESTINIAN TERRITORY Occupied": "pse",
    "PS": "pse",
    "PSE": "pse",
    "State of Palestine": "pse",
    "West Bank and Gaza": "pse",
    "Gaza Strip": "pse_gaza",
    "GZ": "pse_gaza",
    "West Bank": "pse_west_bank",
    "French Polynesia": "pyf",
    "PF": "pyf",
    "PYF": "pyf",
    "QA": "qat",
    "QAT": "qat",
    "Qatar": "qat",
    "RÃ©union": "reu",
    "RE": "reu",
    "REU": "reu",
    "Reunion": "reu",
    "Réunion": "reu",
    "RO": "rou",
    "Romania": "rou",
    "ROU": "rou",
    "RU": "rus",
    "RUS": "rus",
    "Russia": "rus",
    "RUSSIA FEDERATION": "rus",
    "Russian Federation": "rus",
    "RW": "rwa",
    "RWA": "rwa",
    "Rwanda": "rwa",
    "SA": "sau",
    "SAU": "sau",
    "Saudi Arabia": "sau",
    "Serbia and Montenegro": "scg",
    "Serbia_Montenegro": "scg",
    "YUGOSLAVIA (MONTENEGRO & SERBIA)": "scg",
    "Serbia excluding Kosovo": "scg_ex_kos",
    "Serbia_excluding_Kosovo": "scg_ex_kos",
    "REPUBLIC OF SUDAN": "sdn",
    "SD": "sdn",
    "SDN": "sdn",
    "Sudan": "sdn",
    "SEN": "sen",
    "Senegal": "sen",
    "SN": "sen",
    "GS": "sgero_a_ssandw",
    "SGS": "sgero_a_ssandw",
    "South Georgia and the South Sandwich Islands": "sgero_a_ssandw",
    "SG": "sgp",
    "SGP": "sgp",
    "Singapore": "sgp",
    "Saint Helena": "shn",
    "SH": "shn",
    "SHN": "shn",
    "St. Helena": "shn",
    "SJ": "sjm",
    "SJM": "sjm",
    "Svalbard": "sjm",
    "SVALBARD AND JAN MAYEN ISLANDS": "sjm",
    "SB": "slb",
    "SLB": "slb",
    "Solomon Isl.": "slb",
    "Solomon Islands": "slb",
    "Sierra Leone": "sle",
    "Sierra_Leone": "sle",
    "SierraLeo": "sle",
    "SL": "sle",
    "SLE": "sle",
    "El Salvador": "slv",
    "SLV": "slv",
    "SV": "slv",
    "San Marino": "smr",
    "SM": "smr",
    "SMR": "smr",
    "SO": "som",
    "SOM": "som",
    "Somalia": "som",
    "Somaliland": "som_somland",
    "South Ossetia": "sosset",
    "South_Ossetia": "sosset",
    "PM": "spm",
    "SAINT PIERRE AND MIQUELON": "spm",
    "Saint-Pierre-et-Miquelon": "spm",
    "SPM": "spm",
    "St. Pierre & Miquelon": "spm",
    "St.-Pierre-et-Miquelon": "spm",
    "RS": "srb",
    "Serbia": "srb",
    "SRB": "srb",
    "REPUBLIC OF SOUTH SUDAN": "ssd",
    "South â€Žsudan": "ssd",
    "South Sudan": "ssd",
    "SS": "ssd",
    "SSD": "ssd",
    "Sudan South": "ssd",
    "BL": "stbar",
    "BLM": "stbar",
    "Saint Barthélemy": "stbar",
    "St. Barth?©lemy": "stbar",
    "St. Barthélemy": "stbar",
    "Saint Martin": "stmar",
    "St. Martin": "stmar",
    "Sao Tome & Principe": "stp",
    "Sao Tome and Principe": "stp",
    "São Tomé and Principe": "stp",
    "São Tomé and Príncipe": "stp",
    "Sao_Tome_and_Principe": "stp",
    "ST": "stp",
    "STP": "stp",
    "SR": "sur",
    "SUR": "sur",
    "Suriname": "sur",
    "SK": "svk",
    "Slovak Rep": "svk",
    "Slovak Rep.": "svk",
    "Slovak Republic": "svk",
    "Slovakia": "svk",
    "SVK": "svk",
    "SI": "svn",
    "Slovenia": "svn",
    "SVN": "svn",
    "SE": "swe",
    "SWE": "swe",
    "Sweden": "swe",
    "Swaziland": "swz",
    "SWZ": "swz",
    "SZ": "swz",
    "SAINT MARTIN (DUTCH PORTION)": "sxm",
    "Sint Maarten (Dutch part)": "sxm",
    "SX": "sxm",
    "SXM": "sxm",
    "SC": "syc",
    "Seychelles": "syc",
    "SYC": "syc",
    "SY": "syr",
    "SYR": "syr",
    "Syria": "syr",
    "SYRIAN ARAB REP": "syr",
    "Syrian Arab Republic": "syr",
    "TC": "tca",
    "TCA": "tca",
    "Turks and Caicos": "tca",
    "Turks and Caicos Islands": "tca",
    "Chad": "tcd",
    "TCD": "tcd",
    "TD": "tcd",
    "TG": "tgo",
    "TGO": "tgo",
    "Togo": "tgo",
    "TH": "tha",
    "THA": "tha",
    "Thailand": "tha",
    "Tajikistan": "tjk",
    "TJ": "tjk",
    "TJK": "tjk",
    "TK": "tkl",
    "TKL": "tkl",
    "Tokelau": "tkl",
    "TKM": "tkm",
    "TM": "tkm",
    "Turkmenistan": "tkm",
    "Dem. Republic of Timor-Leste": "tls",
    "East Timor": "tls",
    "Timor Leste": "tls",
    "T'imor', East": "tls",
    "Timor-Leste": "tls",
    "Timor-Leste (Formerly East Timor)": "tls",
    "TL": "tls",
    "TLS": "tls",
    "TO": "ton",
    "TON": "ton",
    "Tonga": "ton",
    "Transnistria": "transn",
    "Trinidad": "tto",
    "Trinidad & Tobago": "tto",
    "Trinidad and Tobago": "tto",
    "TT": "tto",
    "TTO": "tto",
    "TN": "tun",
    "TUN": "tun",
    "Tunisia": "tun",
    "TR": "tur",
    "TUR": "tur",
    "Turkey": "tur",
    "TUV": "tuv",
    "Tuvalu": "tuv",
    "TV": "tuv",
    "Taiwan": "twn",
    "Taiwan Province of China": "twn",
    "TW": "twn",
    "TWN": "twn",
    "Tanzania": "tza",
    "Tanzania (United Republic of)": "tza",
    "T'anzania', U. Rep. of": "tza",
    "TANZANIA, UNITED REPUBLIC OF": "tza",
    "TZ": "tza",
    "TZA": "tza",
    "United Republic of Tanzania": "tza",
    "UG": "uga",
    "UGA": "uga",
    "Uganda": "uga",
    "UA": "ukr",
    "UKR": "ukr",
    "Ukraine": "ukr",
    "Uruguay": "ury",
    "URY": "ury",
    "UY": "ury",
    "U.S.": "usa",
    "U.S.A.": "usa",
    "United States": "usa",
    "United States of America": "usa",
    "US": "usa",
    "USA": "usa",
    "UM": "usa_minor_out_isl",
    "UMI": "usa_minor_out_isl",
    "US Minor Outlying Islands": "usa_minor_out_isl",
    "US-UM": "usa_minor_out_isl",
    "Soviet Union": "ussr",
    "U.S.S.R.": "ussr",
    "USS": "ussr",
    "USSR": "ussr",
    "UZ": "uzb",
    "UZB": "uzb",
    "Uzbekistan": "uzb",
    "Saint Vincent and the Grenadines": "vct",
    "St Vincent & the Grenadines": "vct",
    "St. Vincent & The Grenadines": "vct",
    "St. Vincent and G.": "vct",
    "St. Vincent and the Grenadines": "vct",
    "VC": "vct",
    "VCT": "vct",
    "VE": "ven",
    "VEN": "ven",
    "Venezuela": "ven",
    "Venezuela (Bolivarian Republic of": "ven",
    "Venezuela (Bolivarian Republic of)": "ven",
    "V'enezuela', RB": "ven",
    "British Virgin Islands": "vgb",
    "VG": "vgb",
    "VGB": "vgb",
    "VIRGIN ISLANDS (BRITISH)": "vgb",
    "United States Virgin Islands": "vir",
    "VI": "vir",
    "VIR": "vir",
    "Virgin Islands (U.S.)": "vir",
    "Viet Nam": "vnm",
    "Vietnam": "vnm",
    "VN": "vnm",
    "VNM": "vnm",
    "Vanuatu": "vut",
    "VU": "vut",
    "VUT": "vut",
    "Wallis and Futuna": "wlf",
    "WALLIS AND FUTUNA ISLANDS": "wlf",
    "Wallis et Futuna": "wlf",
    "WF": "wlf",
    "WLF": "wlf",
    "Samoa": "wsm",
    "Samoa (Western)": "wsm",
    "WS": "wsm",
    "WSM": "wsm",
    "YE": "yem",
    "YEM": "yem",
    "Yemen": "yem",
    "Yemen Republic": "yem",
    "Y'emen', Rep.": "yem",
    "FORMER YEMEN": "yem_north",
    "North Yemen (former)": "yem_north",
    "North_Yemen": "yem_north",
    "Yemen Arab Republic (Former)": "yem_north",
    "FORMER DEMOCRATIC YEMEN": "yem_south",
    "South Yemen (former)": "yem_south",
    "South_Yemen": "yem_south",
    "Yemen Democratic (Former)": "yem_south",
    "Yugoslavia": "yug",
    "YUGOSLAVIA (FORMER SOCIALIST FEDERAL REPUBLIC)": "yug",
    "South Africa": "zaf",
    "South Africa Republic": "zaf",
    "South_Africa": "zaf",
    "ZA": "zaf",
    "ZAF": "zaf",
    "Zambia": "zmb",
    "ZM": "zmb",
    "ZMB": "zmb",
    "Zimbabwe": "zwe",
    "ZW": "zwe",
    "ZWE": "zwe"
};
